### ISSUE TITLE
Can't update publishing attributes on an image

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#83] opened 2015-12-15 19:00 UTC
I don't think this is an issue with `azurectl` per se, but this seems the best place to track it.

When trying to update the extended attributes on an image `azurectl compute image update ...`, I got the following error response:

```
ERROR: AzureOsImageUpdateError: 'The element(s) "eula,icon_uri,image_family,privacy_uri,published_date,small_icon_uri" could not be updated. Please check if your account is registered as image publisher'
```

**Comment by schaefi** [comment] 2015-12-15 20:20
Hmm, no good news

When I implemented the update command I realized that we don't get any error message back from the API. Thus azurectl runs a getimage() call after it sent the update request. The result is compared with the expected values. If those values are not the ones you wanted to set you get this error message telling which values can't be set

The problem is I have no idea why because we don't get any error from the API

Thus I don't know how we should fix this in the scope of azurectl or even the SDK

**Comment by bear454** [comment] 2016-01-18 22:22
I think I've found the underlying issue :D

**Comment by bear454** [comment] 2016-01-19 01:13
For reference, here's the code for the powershell tool that performs the same operation:

https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Compute/Commands.ServiceManagement/IaaS/DiskRepository/UpdateAzureVMImage.cs

**Comment by bear454** [comment] 2016-01-19 01:14
And here's the REST endpoint:

https://msdn.microsoft.com/en-us/library/azure/jj157198.aspx

**Comment by schaefi** [comment] 2016-01-19 08:30
I'm confused :confused: the powershell tool does basically the same than azurectl if I got it the right.
But it does not work for us while it works for you when using powershell

???

and why can this bug be closed if azurectl still can't do what we need ? :smile:

**Comment by bear454** [comment] 2016-01-19 14:16
Github closed it automatically based on my comment in https://github.com/Azure/azure-sdk-for-python/pull/511

**Comment by schaefi** [comment] 2016-01-19 14:24
ahh :smile:

**Comment by schaefi** [comment] 2016-01-19 16:12
ok thanks for clarification, this issue will be solved in the sdk and does not touch azurectl

closing

**Closed by schaefi** 2016-01-19 16:12 UTC
Labels: bug
